### ISSUE TITLE
Have you tried running it with a sapper? 

### ISSUE THREAD

**Issue by stilet** [dopry/svelte-oidc#1]
Have you tried running it with a sapper? Unfortunately, it didn't work out.

**Comment by dopry** [comment]
Well it's not sapper-OIDC, and you're probably not handling SSR properly as
that is the most likely reason it would work with svelte and not sapper

**Comment by dopry** [comment]
What specifically didn't work out for you?

**Comment by nikibreg** [comment]
[It needs to be SSR compatible to work](https://sapper.svelte.dev/docs#Making_a_component_SSR_compatible)

**Comment by nikibreg** [comment]
It needs to be [SSR compatible](https://sapper.svelte.dev/docs#Making_a_component_SSR_compatible) to work

**Comment by dopry** [comment]
@nikibreg @stillet or write your sapper markup so that you don't load the OIDC Context server side.  This is a pure SPA implementation of Auth. SSR isn't my target audience right now.  Implementing the SSR support would delay loading and auth in the spa. IT would also require that user credentials are provided on the server... Which isn't really the model I'm using the library for.  I'd be open to someone adding the feature. https://github.com/auth0/nextjs-auth0 has a decent implementation for SSR auth IIRC.

**Comment by dopry** [comment]
I updated the docs a bit to call out that the module isn't necessarily SSR compatible.
